/**
 * Single source of truth for navigation menu Feature IDs, matching database navigation_menus table.
 */
export const MENU_FEATURE_IDS = {
  DASHBOARD: 1,
  USERS_MODULE: 2,
  EVENTS_MODULE: 3,
  EVENT_PAGE: 4,
  CALENDAR: 5,
  GALLERY: 6,
  FINANCE_MODULE: 7,
  CONTRIBUTION: 8,
  PAYMENT_HISTORY: 9,
  CALCULATION: 10,
  EXPENSE: 11,
  SUPPORT_TICKET: 12,
  TOOLS_MODULE: 13,
  TOOLS_USERS: 14,
  ROLES: 15,
  USER_RIGHTS: 16,
  EVENT_TYPES: 17,
  BUDGET_CALCULATION: 18,
  TYPES: 19,
  STATUS: 20,
  EXIT_PROCESS: 21,
  SETTINGS: 22,
  REPORTS: 23,

  // Users Actions (ParentID: 2)
  USERS_VIEW: 24,
  USERS_ADD: 25,
  USERS_EDIT: 26,
  USERS_DELETE: 27,
  USERS_IMPORT_EXCEL: 28,
  USERS_EXPORT: 29,
  USERS_UPDATE: 30,

  // Event Actions (ParentID: 4)
  EVENT_VIEW: 31,
  EVENT_ADD: 32,
  EVENT_EDIT: 33,
  EVENT_DELETE: 34,
  EVENT_EXPORT: 35,
  EVENT_ADD_PHOTOS: 54,
  EVENT_VIEW_PHOTOS: 55,
  EVENT_ADD_EXPENSE: 56,
  EVENT_VIEW_EXPENSE: 57,

  // Gallery Actions (ParentID: 6)
  GALLERY_VIEW: 36,
  GALLERY_ADD: 37,
  GALLERY_EDIT: 38,
  GALLERY_DELETE: 39,
  GALLERY_EXPORT: 40,

  // Contribution Actions (ParentID: 8)
  CONTRIBUTION_SUBMIT: 41,
  CONTRIBUTION_AUTHORITY_UPDATE: 42,
  CONTRIBUTION_RAISE_SUPPORT: 43,

  // Expense Actions (ParentID: 11)
  EXPENSE_VIEW: 44,
  EXPENSE_VERIFY: 45,
  EXPENSE_EDIT: 46,
  EXPENSE_DELETE: 47,
  EXPENSE_ADD: 48,

  // Support Ticket Actions (ParentID: 12)
  SUPPORT_TICKET_ADD: 49,
  SUPPORT_TICKET_VIEW: 50,
  SUPPORT_TICKET_VERIFY: 51,
  SUPPORT_TICKET_EDIT: 52,
  SUPPORT_TICKET_DELETE: 53,
};

export default MENU_FEATURE_IDS;
